---
repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-tabs

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: name-tests-test
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-symlinks
      - id: detect-private-key
      - id: check-ast
      - id: debug-statements

  - repo: https://github.com/pycqa/pydocstyle.git
    rev: 6.3.0
    hooks:
      - id: pydocstyle

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.9.0
    hooks:
      - id: black

  # Enable this in repositories with python packages.
  # - repo: https://github.com/mgedmin/check-manifest
  #   rev: '0.39'
  #   hooks:
  #     - id: check-manifest

  - repo: https://github.com/s-weigand/flake8-nb
    rev: v0.5.3
    hooks:
      - id: flake8-nb
        additional_dependencies: ['pep8-naming']
        # Ignore all format-related checks as Black takes care of those.
        args: ['--ignore', 'E2,W5', '--select', 'E,W,F,N', '--max-line-length=130']
